### ISSUE TITLE
Automate or remove mirror

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/rubygem-asciidoctor-rpm#10]
@ktdreyer @fale @voxik To avoid confusion, I'd either like to have this repository set up as an autonomous mirror or just remove it. How would you advise proceeding. Can the fedorahosted repository handle mirroring to an external repository?

If we decide to keep the repository, we should shut down the issue tracker since this is not the primary repository. However, we should document the official issue tracker? Is it this? https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&component=rubygem-asciidoctor&product=Fedora

**Comment by mojavelinux** [comment]
The same goes for this RPM: https://github.com/asciidoctor/rubygem-asciidoctor-pdf-rpm

**Comment by voxik** [comment]
I don't even know that these repositories exists :blush: and personally I am not convinced of usefulness of repositories like this. If the mirroring was be possible, be it, but then the Fedora repository would have to be the canonical source anyway.

**Comment by mojavelinux** [comment]
I'll clarify why the repository exists, though I'm not necessarily defending it:

1. It allows me to count contributions to Asciidoctor for this page: https://asciidoctor.org/contributors/
   * I could get this information a different way using `git log`
2. It acts as a gateway for the community to discover the RPM source by browsing through the asciidoctor organization on GitHub
   * This could be solved by the documentation, which would provide a more direct and visible pathway

One idea for the mirror would be to use a CI job to shuffle commits from the upstream to this mirror. But before committing to setting that up, we have to first determine if the mirror would provide value (aside from the reasons I mentioned).

**Comment by mojavelinux** [comment]
By value, what I'm curious about is whether the mirror helps attract contributions. If it doesn't, then I'd say it has no value.

**Comment by mojavelinux** [comment]
Is the rubygem-asciidoctor repository available on pagure.io? If not, can it be migrated there?

**Comment by mojavelinux** [comment]
https://src.fedoraproject.org/rpms/rubygem-asciidoctor-pdf is also being mirrored now.
